manifest:
  projects:
    - name: nrf
      url: https://github.com/nrfconnect/sdk-nrf
      revision: v2.0.2
      import: true
      import:
        path-blocklist: modules/lib/ticos-firmware-sdk
    - name: ticos-firmware-sdk
      url: https://github.com/ticos/ticos-firmware-sdk
      path: modules/lib/ticos-firmware-sdk
      revision: master
  self:
    path: ticos_demo_app
    import: submanifests
