manifest:
  remotes:
    - name: nrf-connect-sdk
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      url: https://github.com/nrfconnect/sdk-nrf
      revision: v2.0.2
      import: true

    # Adding the ticos-firmware-sdk module here overrides the version the nRF
    # Connect SDK would normally import above
    - name: ticos-firmware-sdk
      url: https://github.com/ticos/ticos-firmware-sdk
      path: modules/lib/ticos-firmware-sdk
      revision: master
  self:
    path: ticos_demo_app
