name: on_ticos_framework_publish
run-name: ${{ github.actor }} is publishing the codegen path 🚀
on:
  release:
    types: [published]

jobs:
  updateServerless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Prepare service file
        run: cp -r scripts/codegen/  .sls.tencent
      - name: Deploy to serverless environment
        run: npx serverless@^2.x.x deploy
      
      