name: on_ticos_sdk_release
run-name: ${{ github.actor }} is publishing the codegen path 🚀
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  updateServerless:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_PLATFORM_VENDOR: tencent
      TENCENT_SECRET_ID: ${{ github.ref_name == 'develop'  && secrets.DEV_TENCENT_SECRET_ID || secrets.PROD_TENCENT_SECRET_ID }}
      TENCENT_SECRET_KEY: ${{ github.ref_name == 'develop' && secrets.DEV_TENCENT_SECRET_KEY || secrets.PROD_TENCENT_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Prepare service file
        run: cp -r scripts/codegen/.  .sls.tencent
      - name: Deploy to serverless environment
        run: npx serverless-cloud-framework deploy --target .sls.tencent
      
      
